"""first migration

Revision ID: 20071d0d310b
Revises:
Create Date: 2024-11-08 20:08:46.363865

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "20071d0d310b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
