"""Add User Test

Revision ID: 5bd9aa351cb6
Revises: a6fb07370d28
Create Date: 2024-11-01 11:32:21.390785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd9aa351cb6'
down_revision: Union[str, None] = 'a6fb07370d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_perfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellidos', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_id')
    )
    op.create_index(op.f('ix_usuario_perfiles_id'), 'usuario_perfiles', ['id'], unique=False)
    op.drop_index('ix_suppliers_id', table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('auth_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='suppliers_pkey'),
    sa.UniqueConstraint('auth_id', name='suppliers_auth_id_key')
    )
    op.create_index('ix_suppliers_id', 'suppliers', ['id'], unique=False)
    op.drop_index(op.f('ix_usuario_perfiles_id'), table_name='usuario_perfiles')
    op.drop_table('usuario_perfiles')
    # ### end Alembic commands ###
